#!/bin/env bash


set -eu


function log_error()
{
	>&2 echo "[ERROR] $*"
}


# For a given number, log an error and exit with the number as exit status.
function log_exit()
{
	local exit_status="$1"

	log_error "Commit failed with exit status $exit_status."
	log_error "Fix the errors and commit again."

	exit "$exit_status"
}


# Check that the names of the files staged do not contain non-ascii characters
# and exit with non-zero status otherwise.
function check_ascii_filenames()
{
	if test "$(
		git diff --staged --name-only -z \
			| LC_ALL=C tr -d '[ -~]\0' \
			| wc -c
	)" != 0; then
		log_error "All file names should contain only non-ascii characters."
		log_exit 1
	fi
}


# Check that the files staged contain no whitespace errors or conflict markers
# and exit with non-zero status if this does not hold.
function check_whitespaces_and_conflict_markers()
{
	if ! git diff --check --staged; then
		log_exit 2
	fi
}


# Check that the files staged end with a newline and exit with non-zero status
# otherwise.
function check_newline_eof()
{
	if test "$(
		git diff --staged --name-only \
			| xargs -I{} tail --bytes 1 {} \
			| wc -w
	)" != 0; then
		log_error "All files should end with a new line."
		log_exit 3
	fi
}


function main()
{
	check_ascii_filenames
	check_whitespaces_and_conflict_markers
	check_newline_eof
}


main
